apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-security-analyzer
spec:
  selector:
    matchLabels:
      app: istio-security-analyzer
  template:
    metadata:
      labels:
        app: istio-security-analyzer
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
			  # TODO(vpn-soft): image path need to be changed according to image registery
        image: istio-security-analyzer:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: istio-security-analyzer
spec:
  type: ClusterIP
  selector:
    app: istio-security-analyzer
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
